### ISSUE TITLE
Backend error in IDE for partial constructor syntax

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#1993]
This code, in the IDE
```ceylon
class Foo {
    shared new Bar
}
```
causes this error 
```
The Ceylon Java backend compiler failed abnormally
```

**Comment by tombentley** [comment]
I think this might have been fixed by ceylon/ceylon-spec#1184 because I just get a typechecker error and no backend error. Could you confirm please @sgalles?

**Comment by sgalles** [comment]
@tombentley I still see the backend error in the IDE.
I emphasize that it is only in the IDE. No problem with the CLI.
And also in the IDE I see :
```
missing parameter list in constructor declaration: 'Bar' must have a parameter list
```
And I don't see this error with the CLI either.

**Comment by sgalles** [comment]
Oh, and also @tombentley  the code must be written at top level. It does not happen with the same code in a method.

**Comment by sgalles** [comment]
Ah ! @tombentley , @davidfestal I've re-cloned my ceylon-ide-eclipse and **now** I don't see the backend error anymore. So it seems that somehow it was related to my environnement.
@tombentley then I close the issue. Thanks.

**Comment by sgalles** [comment]
Grrr...@tombentley , @davidfestal yes I still reproduce it eventually...I just had deactivated the Java compilation in my test project...my bad...reopening...

**Comment by jvasileff** [comment]
I get all of the above on the IDE on both a new build and a late December build. By that, I mean three type checker errors, `compiler bug: null at ... ClassTransformer.java:1097`, and `The Ceylon Java backend compiler failed abnormally`.

I don't know what the normal process is, but it seems like for this specific case, the Java backend continues the compilation attempt despite the type checker errors.

And there's some additional weirdness - the error markers for `null at ... 1097` can appear in an unrelated files (even `package.ceylon`), sometimes with an additional marker appearing every seven seconds.

**Comment by jvasileff** [comment]
![1993 screen shot](https://cloud.githubusercontent.com/assets/236050/5692074/7d825f5a-98b3-11e4-8814-86ada0cada93.png)

**Comment by tombentley** [comment]
It's likely that my fix for #1994 has fixed this bug. I'd be grateful if someone who's been able to reproduce this bug could try it out and let me know if they can still reproduce it. Thanks.

**Comment by sgalles** [comment]
@tombentley Indeed, I can't reproduce now (with the JVM compilation activated ;)  )
So, I guess it can be closed now.

**Comment by jvasileff** [comment]
> Indeed, I can't reproduce now

ditto; looks good!

**Comment by tombentley** [comment]
Closing then. Thanks @sgalles and @jvasileff .
