### ISSUE TITLE
Incompatible type on some tuples in ceylon.ast

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2026]
Some `ceylon.ast` nodes can’t use the most precise possible type for `children` because it causes javac errors. This has previously been reported as #1728 and #1834, but in both cases I oversimplified the `ceylon.ast` situation with the result that while the reduced test case was indeed fixed, `ceylon.ast` compilation still fails.

To see this, check out the [`unWorkaroundCompilerBug` branch](https://github.com/ceylon/ceylon.ast/tree/unWorkaroundCompilerBug) of `ceylon.ast` and try to build the project (i. e. `ant clean test`). As of 2015-01-29 18:00 CET, I get [these errors](https://gist.github.com/lucaswerkmeister/f3bbc05fca4bd398165a):

> error: incompatible types
> ```ceylon
>             children = [importAlias, name, nestedImports];
>                                            ^
> ```
>   required: `Sequential<? extends Node>`
>   found:    `Sequence<CAP#1>`
>   where `CAP#1` is a fresh type-variable:
>   
>     CAP#1 extends Object from capture of ? extends Object

seven times at different locations.

Unfortunately, so far I haven’t succeeded in producing a reasonably small test case that exposes the same bug.

**Comment by lucaswerkmeister** [comment]
Alright, I *finally* have a smaller code sample. I committed it in [this gist](https://gist.github.com/lucaswerkmeister/62a5fb4f16d2ac555264), which I’ll update as I try to further reduce the code. (Clone it and see the commit messages.)

**Comment by lucaswerkmeister** [comment]
Oh, and in that gist, if you build it from the command line, you only see errors in `ImportFunctionValueElement.ceylon`, whereas the IDE will show you the same errors in `ImportTypeElement.ceylon` as well. Looks like the CLI aborts after the first erroneous file.

**Comment by lucaswerkmeister** [comment]
I’ve added a second branch to the gist: in `noName`, you can see how one change (the removal of the `name` parameter+attribute) moves the error into the `else` branch. to an assignment of `[]`. See the commit message.

**Comment by lucaswerkmeister** [comment]
Only 43 LOC total… I think that’s as minimal as I can make that sample (except by trimming blank lines). I’m done.

When you think you’ve fixed the bug, test it against the first revision of the gist too ([32e54c4](https://gist.github.com/lucaswerkmeister/62a5fb4f16d2ac555264/32e54c43a9b2de9def76c15316f5087c71c85ee3)), and if possible against `ceylon.ast`’s `unWorkaroundCompilerBug` branch as well, just to make sure.

**Comment by lucaswerkmeister** [comment]
And I’ve found the reason why I was never able to reproduce the bug manually – it disappears if you move everything into a single file. *heavy breathing*

**Comment by quintesse** [comment]
@lucaswerkmeister Could you test this with the latest version from master? I just tried the latest revision of the gist and that seems to compile just fine. Maybe it was fixed in the mean time?

**Comment by lucaswerkmeister** [comment]
I’m still getting the error both on the gist and on `ceylon.ast`.

**Comment by quintesse** [comment]
Yes, I'm able to reproduce it now... the *order* in which the files are presented to the compiler has effect on the outcome! Wow.

**Comment by lucaswerkmeister** [comment]
WTF

so how did you get a different order? re-clone resulting in different file system order?

**Comment by quintesse** [comment]
No, I added a test to our test suite where you specify the files to compile as a list. I just added the files in the order they appear in your Gist and they compile without a problem, but on the command line with `ceylon compile tmp` I got an error. When I put the files in the test in the same order as they appeared in the verbose output on the CLI I suddenly got the same error.

In fact I get the error with `ceylon compile tmp` but not with `ceylon compile source/tmp/*.ceylon`

**Comment by lucaswerkmeister** [comment]
Amazing.

**Comment by quintesse** [comment]
So for example, this order fails:

```java
        compile("bug20xx/bug2026/ImportTypeElement.ceylon", "bug20xx/bug2026/ImportFunctionValueElement.ceylon",
                "bug20xx/bug2026/module.ceylon", "bug20xx/bug2026/Node.ceylon", "bug20xx/bug2026/Identifier.ceylon",
                "bug20xx/bug2026/ImportElement.ceylon", "bug20xx/bug2026/package.ceylon",
                "bug20xx/bug2026/ImportElements.ceylon"
                );
```

while this succeeds:

```java
        compile("bug20xx/bug2026/module.ceylon", "bug20xx/bug2026/package.ceylon", "bug20xx/bug2026/Identifier.ceylon",
                "bug20xx/bug2026/ImportElement.ceylon", "bug20xx/bug2026/ImportElements.ceylon",
                "bug20xx/bug2026/ImportFunctionValueElement.ceylon", "bug20xx/bug2026/ImportTypeElement.ceylon",
                "bug20xx/bug2026/Node.ceylon");
```

**Comment by quintesse** [comment]
The differences in generated code are minimal but important, in `ImportFunctionValueElement` I see this working code:

```java
        .com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.ImportElements nestedImports$1;
        if ((nestedImports$1 = getNestedImports()) != null) {
            final .com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.ImportElements nestedImports$3 = nestedImports$1;
            children = (.ceylon.language.Sequential<? extends .com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.Node>)(.ceylon.language.Sequential)(.ceylon.language.Sequence<? extends .java.lang.Object>).ceylon.language.Tuple.instance(.com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.union(.com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.Identifier.$TypeDescriptor$, .com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.ImportElements.$TypeDescriptor$), new .java.lang.Object[]{
                    getName(),
                    nestedImports$3});
        } else {
            final .java.lang.Object nestedImports$2 = nestedImports$1;
            children = (.ceylon.language.Sequence<? extends .com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.Identifier>).ceylon.language.Tuple.instance(.com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.Identifier.$TypeDescriptor$, new .java.lang.Object[]{getName()});
        }
```

versus this code that fails:

```java
        .com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.ImportElements nestedImports$5;
        if ((nestedImports$5 = getNestedImports()) != null) {
            final .com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.ImportElements nestedImports$7 = nestedImports$5;
            children = (.ceylon.language.Sequence<? extends .java.lang.Object>).ceylon.language.Tuple.instance(.com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.union(.com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.Identifier.$TypeDescriptor$, .com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.ImportElements.$TypeDescriptor$), new .java.lang.Object[]{
                    getName(),
                    nestedImports$7});
        } else {
            final .java.lang.Object nestedImports$6 = nestedImports$5;
            children = (.ceylon.language.Sequence<? extends .com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.Identifier>).ceylon.language.Tuple.instance(.com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026.Identifier.$TypeDescriptor$, new .java.lang.Object[]{getName()});
        }
```

Looking at the numbering it seems the two code blocks have been generated in a different order, which isn't what causes the problem, but there's also a cast missing in the failing code.

**Comment by quintesse** [comment]
The only other difference I see is in the generated meta data:

```java
    @.ceylon.language.SharedAnnotation$annotation$
    @.ceylon.language.ActualAnnotation$annotation$
    @.java.lang.Override
    @.com.redhat.ceylon.compiler.java.metadata.TypeInfo(
            value = "ceylon.language::Tuple<com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026::Identifier|com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026::ImportElements,com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026::Identifier,ceylon.language::Empty|ceylon.language::Tuple<com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026::ImportElements,com.redhat.ceylon.compiler.java.test.issues.bug20xx.bug2026::ImportElements,ceylon.language::Empty>>",
            erased = true,
            untrusted = true)
    public final .ceylon.language.Sequential getChildren() {
        return children;
    }
```

The working version has `untrusted=true` here while it's missing from the failing version.

**Comment by quintesse** [comment]
Ok, so this seems to have to do with the way the `BoxingDeclarationVisitor` sets the "untrusted type", the value of this can depend on the value of the trusted type of a refined declaration. If that declaration hasn't been visited yet it will use the wrong value for it and therefore the final result will be wrong.

I can think of several not-so-nice ways of solving this:
 - change the call to `CodegenUtil.hasUntrustedType()` in line 990 of `AbstractTransformer` and change it into something that re-calculates the untrusted type state each time.
 - or change the type of `untrustedType` in `TypedDeclaration` to a `Boolean` and make sure we either set it to true or false after being intitialized, so `null` could mean we still haven't calculated it and first do that (it's like point 1 but more efficient, at the cost of an reference field in `TypedDeclaration`)

So maybe @FroMage can shine his light on this because maybe there's a better way that I'm not seeing.

**Comment by quintesse** [comment]
And you could add another point to the above list:

 - make sure the `BoxingDeclarationVisitor` visits declarations in the order of least refined to most refined

But I'm guessing that would be a mayor change and maybe not so easy to do.

**Comment by tombentley** [comment]
The test for this issue now passes, but I suspect that's due to the change I made for #2048, rather than the underlying problem being fixed. So a fix for that is still needed.

**Comment by lucaswerkmeister** [comment]
> The test for this issue now passes

Thanks, then I can finally merge that branch :)

**Comment by FroMage** [comment]
Let's move it to 1.3
