### ISSUE TITLE
Interop and overloading issue

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-compiler#2318]
Given the following code:

```Java
public interface JavaInterface {

    void apply(StringBuffer buf);
    
    void apply(char ch, int i1);
}
```

and 

```ceylon
import java.lang {
    StringBuffer
}

interface CeylonMixin satisfies JavaInterface {
    shared actual void apply(StringBuffer buf) { }
    shared actual void apply(Character ch, Integer i1) { }
}

class Cls() satisfies CeylonMixin {
}
```

I get the following error:

> Cls is not abstract and does not override abstract method apply(char,long) in CeylonMixin

**Comment by gavinking** [comment]
This is because no `$impl` delegating methods are generated in the implementing class.

**Comment by FroMage** [comment]
Fixed.

**Comment by bjansen** [comment]
Sorry, my real test case is a little more complex than that, one of the two functions is annotated `default`, and overriden in the concrete class:

```
import java.lang {
    StringBuffer
}

interface CeylonMixin satisfies JavaInterface {
    shared default actual void apply(StringBuffer buf) { }
    shared actual void apply(Character ch, Integer i1) { }
}

class Cls() satisfies CeylonMixin {
    
    shared actual void apply(StringBuffer buf) => super.apply(buf);
}
```

In this case, it still doesn't work:

```
Mymodule.Cls is not abstract and does not override abstract method apply(char,int) in mymodule.CeylonMixin
```

**Comment by FroMage** [comment]
So this one is more complex, and due to the model's `getMember` which we call on `Cls` with `name = "apply"` and the proper `signature = [Character, Integer]` which finds an inexact match in `Cls.apply(StringBuffer)` because it doesn't see that it's overloaded. I believe that's a question for @gavinking: how can we support this?

**Comment by gavinking** [comment]
This is a known limitation isn't it? Isn't there another issue open about this?

**Comment by gavinking** [comment]
Wait: perhaps I misunderstood.

**Comment by gavinking** [comment]
Why doesn't it see that it's overloaded?

**Comment by FroMage** [comment]
Because it's not overloaded in the `CeylonMixin` interface, so you don't mark them as overloaded and you don't look up the hierarchy.

**Comment by gavinking** [comment]
But it _is_ overloaded in `CeylonMixin`!

**Comment by FroMage** [comment]
Oh sorry, I mean it's not overloaded in `Cls` (from the last comment with code sample).

**Comment by gavinking** [comment]
Well I just tried this: the typechecker accepts the code and correctly resolves the overloaded method! The only error is from the backend.

**Comment by gavinking** [comment]
The _backend_ gives me the error:

    Hello.Cls is not abstract and does not override abstract method apply(char,int) in hello.Ceylon

But if I click on the little green triangle in the IDE, it takes me to the right overloaded refined declaration. So the _IDE_ certainly knows how to resolve the overload.

**Comment by FroMage** [comment]
Well yes there's an error _because_ when I call `Cls.getMethod("apply", [Integer,Character])` I get `Cls.apply(StringBuffer)`.

**Comment by gavinking** [comment]
But whatever code the typechecker and IDE use to do this works.

**Comment by FroMage** [comment]
OK, so what's the magical code then?

**Comment by gavinking** [comment]
Well I'm not sure what you're trying to do. Are you trying to do the same conceptual thing as resolving `super.apply(int, char)`?

**Comment by FroMage** [comment]
I want to get the most refined version of `apply(int,char)` from `Cls`.

**Comment by gavinking** [comment]
Well that is a question which does not in general have a unique answer. That's why I'm asking.

When I resolve a `super` invocation, you don't get the *most* refined if that is ambiguous. You get the most refined *in common*.

OTOH the IDE does something different that involves handwavy heuristics where `extends` takes priority over `satisfies`.

**Comment by gavinking** [comment]
FTR the strategy I use for `super` is to form the intersection of all supertypes, and then resolve the member against that intersection type. This "trick" is actually specified by the language spec.

**Comment by FroMage** [comment]
So I should get the member, verify that its signature does not match then revert to asking the supertypes? That sounds very convoluted and error-prone. Do you have something that does this correctly in the model module?

**Comment by gavinking** [comment]
> So I should get the member, verify that its signature does not match then revert to asking the supertypes? 

huh? I have no idea what you're proposing here.

> Do you have something that does this correctly in the model module?

I'm trying to explain to you that there is no "correct", at least not as far as you have stated the problem at this point.

It seems the main problem here is you're not really sure what you're trying to do...

**Comment by gavinking** [comment]
To be clear, the question "what is the unique most-refined supertype member with this name and signature" is not a question that has an answer in Ceylon, and therefore there is no method that performs this "correctly".

**Comment by FroMage** [comment]
OK, I see what you mean about ambiguity, but in this case there is no ambiguity, so how would I solve it when there is no ambiguity.

**Comment by gavinking** [comment]
Well like I said `ModelUtil.intersectionOfSupertypes(type).getMember(name, signature)`.

But you have to be prepared to handle the case where this will give you a "wrong" answer. Though perhaps the typechecker has already eliminated those situations for you. I don't know. `Cos I don't know what you're doing this for.

**Comment by FroMage** [comment]
Well, this if for mixin delegation, so in theory the typechecker will reject any ambiguity because the user will be forced to resolve it manually at this point.

Should I only call this method when the normal `getMember` does not return a valid member? I assume it's expensive.

**Comment by FroMage** [comment]
I will still have to call the normal `getMember` because if I find that `Cls` has overridden this method I don't want to generate the mixin delegate method. It's just that I can't trust its return value to be valid :(

**Comment by gavinking** [comment]
Well `intersectionOfSupertypes()` doesn't canonicalize so it's not _that_ expensive.

**Comment by FroMage** [comment]
OK, so `getMember()`, check if the signature matches, if not, try `intersectionOfSupertypes`, but won't that also risk returning me an overload that is invalid?

**Comment by FroMage** [comment]
what if the supertype is `Cls`, for example? Won't that have the exact same problem?

**Comment by gavinking** [comment]
The type checker doesn't support stuff like that. This class doesn't typecheck:

```ceylon
class C() extends Cls() {
    void m() {
        apply(' ', 1);
    }
}
```

This is a known limitation.

**Comment by gavinking** [comment]
The typechecker does, of course, accept this:

```ceylon
class C() extends Cls() {
    void m() {
        (this of Java).apply(' ', 1);
    }
}
```

However, it turns out that this trips up another backend bug:

```
Method apply in class hello.Cls cannot be applied to given types;
  required: java.lang.StringBuffer
  found: char,int
  reason: actual and formal argument lists differ in length
```

Ouch.

Not sure why, the typechecker correctly resolves the target method.

**Comment by FroMage** [comment]
So I'm not sure I can solve this, since it'd be a hack for only the first level. It'd still fail for the second level.

**Comment by gavinking** [comment]
@FroMage I don't follow.

**Comment by FroMage** [comment]
Well, I tried something which works which is to add an optional parameter `boolean onlyExactMatches = false` to `Element.getMember`, `Element.getMemberOrParameter` and `Element.getDirectMember`, and it fixes this issue by ignoring overloads whose signature does not match the one we're looking for. The parameter is defaulted to the previous behaviour and so it's source and binary compatible with the existing contract. Would you accept this change?

**Comment by gavinking** [comment]
I guess.

**Comment by gavinking** [comment]
You probably need to change RefinementVisitor to use it.

**Comment by FroMage** [comment]
So that works for solving this case, but it breaks a lot of other code if I specify a signature, because `getMember` will not use `Reference` when looking at supertypes: it only considers `TypeDeclaration` (unapplied), so when looking for `foo(Integer)` it will not consider `foo(T)` as matching even if the type I query this on satisfies `Foo<Integer>`.

**Comment by FroMage** [comment]
@bjansen try now?

I made it work, but as I mentioned it's very fragile in the face of generics and overloading.

**Comment by FroMage** [comment]
Apparently I also fixed the bug @gavinking found with `this of Java`, I added a test for it.

**Comment by bjansen** [comment]
It solves my initial problem, so it's good enough for me. Thanks!
